declare const FILE_EXTENSIONS: {
    audio: string[];
    boxcanvas: string[];
    boxnote: string[];
    code: string[];
    document: string[];
    'docuworks-binder': string[];
    'docuworks-file': string[];
    dwg: string[];
    'excel-spreadsheet': string[];
    'google-docs': string[];
    'google-sheets': string[];
    'google-slides': string[];
    illustrator: string[];
    image: string[];
    indesign: string[];
    keynote: string[];
    numbers: string[];
    pages: string[];
    pdf: string[];
    photoshop: string[];
    'powerpoint-presentation': string[];
    presentation: string[];
    spreadsheet: string[];
    text: string[];
    threed: string[];
    vector: string[];
    video: string[];
    'word-document': string[];
    zip: string[];
};
export { FILE_EXTENSIONS };
