pull_request_rules:
  - name: Automatic strict merge
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - status-success=lint_test_build
      - status-success="Semantic Pull Request"
      - status-success=license/cla
      - label=ready-to-merge
      - label!=do-not-merge
      - title~=^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\([^)]+\))?:\s.+$
    actions:
      merge:
        method: squash
        strict: smart
  - name: Automatic head deletion
    conditions: []
    actions:
      delete_head_branch: {}
