queue_rules:
  - name: Automatic boxmoji merge
    queue_conditions:
      - author=boxmoji
      - base=master
      - files~=^i18n/
      - status-success="Validate"
      - status-success=lint_test_build
      - title~=^(fix)\(i18n\)?:\supdate translations$
    merge_conditions:
      - status-success="Validate"
      - status-success=lint_test_build
    merge_method: squash
  - name: Automatic strict merge
    queue_conditions:
      - base=master
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - status-success="Validate"
      - status-success=license/cla
      - status-success=lint_test_build
      - label=ready-to-merge
      - label!=do-not-merge
      - title~=^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\([^)]+\))?:\s.+$
    merge_conditions:
      - status-success="Validate"
      - status-success=license/cla
      - status-success=lint_test_build
    merge_method: squash
  - name: Automatic devin merge
    queue_conditions:
      - author=devin-ai-integration[bot]
      - base=master
      - "#approved-reviews-by>=1"
      - status-success="Validate"
      - status-success=lint_test_build
      - label=ready-to-merge
      - label!=do-not-merge
      - title~=^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\([^)]+\))?:\s.+$
    merge_conditions:
      - status-success="Validate"
      - status-success=lint_test_build

pull_request_rules:
  - name: Automatic merge
    conditions: []
    actions:
      queue:
