merge_queue:
    max_parallel_checks: 1

pull_request_rules:
    - name: Automatic merge queue
      conditions:
          - -draft
          - base = master
      actions:
          queue:

queue_rules:
    - name: Automatic boxmoji merge
      queue_conditions:
          - author = boxmoji
          - title ~= ^(fix)\(i18n\)?:\supdate translations$
          - files ~= ^i18n/
          - label != do-not-merge
          - status-success = license/cla
          - status-success = lint_pull_request
          - status-success = lint_test_build
      merge_conditions:
          - status-success = lint_pull_request
          - status-success = lint_test_build
      merge_method: squash

    - name: Automatic strict merge
      queue_conditions:
          - title ~= ^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\([^)]+\))?:\s.+$
          - label = ready-to-merge
          - label != do-not-merge
          - status-success = license/cla
          - status-success = lint_pull_request
          - status-success = lint_test_build
          - branch-protection-review-decision = APPROVED
          - "#approved-reviews-by >= 2"
          - "#changes-requested-reviews-by = 0"
          - "#review-threads-unresolved = 0"
      merge_conditions:
          - status-success = license/cla
          - status-success = lint_pull_request
          - status-success = lint_test_build
      merge_method: squash
