const mockRecentItems = {
    next_marker: '',
    limit: 100,
    order: {
        by: 'interacted_at',
        direction: 'DESC',
    },
    entries: [
        {
            type: 'recent_item',
            interaction_type: 'item_preview',
            interacted_at: '2025-01-31T13:40:24-08:00',
            item: {
                type: 'file',
                id: '1222291629977',
                etag: '1',
                name: 'Resume (4).pdf',
                size: 69266,
                parent: {
                    type: 'folder',
                    id: '0',
                    sequence_id: null,
                    etag: null,
                    name: 'All Files',
                },
                extension: 'pdf',
                permissions: {
                    can_download: true,
                    can_preview: true,
                    can_upload: true,
                    can_comment: true,
                    can_rename: true,
                    can_delete: true,
                    can_share: true,
                    can_set_share_access: true,
                    can_invite_collaborator: true,
                    can_annotate: true,
                    can_view_annotations_all: true,
                    can_view_annotations_self: true,
                    can_create_annotations: true,
                    can_view_annotations: true,
                },
                path_collection: {
                    total_count: 1,
                    entries: [
                        {
                            type: 'folder',
                            id: '0',
                            sequence_id: null,
                            etag: null,
                            name: 'All Files',
                        },
                    ],
                },
                modified_at: '2023-05-24T11:43:41-07:00',
                created_at: '2023-05-24T11:43:41-07:00',
                modified_by: {
                    type: 'user',
                    id: '24991742828',
                    name: 'GW',
                    login: 'gw@boxdemo.com',
                },
                has_collaborations: false,
                is_externally_owned: false,
                authenticated_download_url: 'https://dl.boxcloud.com/api/2.0/files/1222291629977/content',
                is_download_available: true,
                representations: {
                    entries: [
                        {
                            representation: 'jpg',
                            properties: {
                                dimensions: '1024x1024',
                                paged: 'false',
                                thumb: 'false',
                            },
                            info: {
                                url: 'https://api.box.com/2.0/internal_files/1222291629977/versions/1334003366777/representations/jpg_1024x1024',
                            },
                            status: {
                                state: 'success',
                            },
                            content: {
                                url_template:
                                    'https://dl.boxcloud.com/api/2.0/internal_files/1222291629977/versions/1334003366777/representations/jpg_1024x1024/content/{+asset_path}',
                            },
                        },
                    ],
                },
                file_version: {
                    type: 'file_version',
                    id: '1334003366777',
                    sha1: 'c60c18bcdc28ed573f7acb440e5d5f1ca9bd2f59',
                },
                sha1: 'c60c18bcdc28ed573f7acb440e5d5f1ca9bd2f59',
                shared_link: {
                    url: 'https://app.box.com/s/6wvvmdmgmo9ky62p054zbtgn1ph78els',
                    download_url: 'https://app.box.com/shared/static/6wvvmdmgmo9ky62p054zbtgn1ph78els.pdf',
                    vanity_url: null,
                    vanity_name: null,
                    effective_access: 'open',
                    effective_permission: 'can_download',
                    is_password_enabled: false,
                    unshared_at: null,
                    download_count: 0,
                    preview_count: 0,
                    access: 'open',
                    permissions: {
                        can_preview: true,
                        can_download: true,
                        can_edit: false,
                    },
                },
                watermark_info: {
                    is_watermarked: false,
                },
            },
            interaction_shared_link: null,
        },
        {
            type: 'recent_item',
            interaction_type: 'item_preview',
            interacted_at: '2025-01-28T11:12:18-08:00',
            item: {
                type: 'file',
                id: '1318276254035',
                etag: '1',
                name: 'Resume (2) (1).pdf',
                size: 69266,
                parent: {
                    type: 'folder',
                    id: '218662304788',
                    sequence_id: '0',
                    etag: '0',
                    name: 'metadataquery',
                },
                extension: 'pdf',
                permissions: {
                    can_download: true,
                    can_preview: true,
                    can_upload: true,
                    can_comment: true,
                    can_rename: true,
                    can_delete: true,
                    can_share: true,
                    can_set_share_access: true,
                    can_invite_collaborator: true,
                    can_annotate: true,
                    can_view_annotations_all: true,
                    can_view_annotations_self: true,
                    can_create_annotations: true,
                    can_view_annotations: true,
                },
                path_collection: {
                    total_count: 2,
                    entries: [
                        {
                            type: 'folder',
                            id: '0',
                            sequence_id: null,
                            etag: null,
                            name: 'All Files',
                        },
                        {
                            type: 'folder',
                            id: '218662304788',
                            sequence_id: '0',
                            etag: '0',
                            name: 'metadataquery',
                        },
                    ],
                },
                modified_at: '2023-09-26T14:04:52-07:00',
                created_at: '2023-09-26T14:04:52-07:00',
                modified_by: {
                    type: 'user',
                    id: '24991742828',
                    name: 'GW',
                    login: 'gw@boxdemo.com',
                },
                has_collaborations: false,
                is_externally_owned: false,
                authenticated_download_url: 'https://dl.boxcloud.com/api/2.0/files/1318276254035/content',
                is_download_available: true,
                representations: {
                    entries: [
                        {
                            representation: 'jpg',
                            properties: {
                                dimensions: '1024x1024',
                                paged: 'false',
                                thumb: 'false',
                            },
                            info: {
                                url: 'https://api.box.com/2.0/internal_files/1318276254035/versions/1442246185235/representations/jpg_1024x1024',
                            },
                            status: {
                                state: 'success',
                            },
                            content: {
                                url_template:
                                    'https://dl.boxcloud.com/api/2.0/internal_files/1318276254035/versions/1442246185235/representations/jpg_1024x1024/content/{+asset_path}',
                            },
                        },
                    ],
                },
                file_version: {
                    type: 'file_version',
                    id: '1442246185235',
                    sha1: 'c60c18bcdc28ed573f7acb440e5d5f1ca9bd2f59',
                },
                sha1: 'c60c18bcdc28ed573f7acb440e5d5f1ca9bd2f59',
                shared_link: {
                    url: 'https://app.box.com/s/4isrn71f96h1q76dluj1a71h6o8d6z17',
                    download_url: 'https://app.box.com/shared/static/4isrn71f96h1q76dluj1a71h6o8d6z17.pdf',
                    vanity_url: null,
                    vanity_name: null,
                    effective_access: 'open',
                    effective_permission: 'can_download',
                    is_password_enabled: false,
                    unshared_at: null,
                    download_count: 0,
                    preview_count: 0,
                    access: 'open',
                    permissions: {
                        can_preview: true,
                        can_download: true,
                        can_edit: false,
                    },
                },
                watermark_info: {
                    is_watermarked: false,
                },
            },
            interaction_shared_link: null,
        },
    ],
};
export default mockRecentItems;
