#!/usr/bin/env node

const fs = require("fs");
const { promisify } = require("util");

const readFile = promisify(fs.readFile);
const writeFile = promisify(fs.writeFile);

async function main() {
  const content = await readFile("./package.json", { encoding: "utf8" });
  const json = JSON.parse(content);
  json.engines = undefined;
  await writeFile("./package.json", JSON.stringify(json, null, 4), { encoding: "utf8" });
}

main();
