import type { Meta, StoryObj } from '@storybook/react';
import ContentExplorer from '../../ContentExplorer';
export declare const metadataView: Story;
export declare const metadataViewV2: Story;
export declare const metadataViewV2SortsFromHeader: Story;
export declare const metadataViewV2WithCustomActions: Story;
export declare const metadataViewV2WithInitialFilterValues: Story;
export declare const sidePanelOpenWithSingleItemSelected: Story;
export declare const metadataViewV2WithBulkItemActionMenuShowsItemActionMenu: Story;
export declare const sidePanelOpenWithMultipleItemsSelected: Story;
declare const meta: Meta<typeof ContentExplorer>;
type Story = StoryObj<typeof meta>;
export default meta;
