// flow-typed signature: a88c581360a8cac3ffd9400f2ad382e6
// flow-typed version: <<STUB>>/react-tether_v1.0.x/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tether'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tether' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tether/dist/react-tether' {
  declare module.exports: any;
}

declare module 'react-tether/dist/react-tether.min' {
  declare module.exports: any;
}

declare module 'react-tether/example/index' {
  declare module.exports: any;
}

declare module 'react-tether/lib/react-tether' {
  declare module.exports: any;
}

declare module 'react-tether/lib/TetherComponent' {
  declare module.exports: any;
}

declare module 'react-tether/src/react-tether' {
  declare module.exports: any;
}

declare module 'react-tether/src/TetherComponent' {
  declare module.exports: any;
}

declare module 'react-tether/tests/test' {
  declare module.exports: any;
}

declare module 'react-tether/webpack.banner' {
  declare module.exports: any;
}

declare module 'react-tether/webpack.config' {
  declare module.exports: any;
}

declare module 'react-tether/webpack.prod.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tether/dist/react-tether.js' {
  declare module.exports: $Exports<'react-tether/dist/react-tether'>;
}
declare module 'react-tether/dist/react-tether.min.js' {
  declare module.exports: $Exports<'react-tether/dist/react-tether.min'>;
}
declare module 'react-tether/example/index.jsx' {
  declare module.exports: $Exports<'react-tether/example/index'>;
}
declare module 'react-tether/lib/react-tether.js' {
  declare module.exports: $Exports<'react-tether/lib/react-tether'>;
}
declare module 'react-tether/lib/TetherComponent.js' {
  declare module.exports: $Exports<'react-tether/lib/TetherComponent'>;
}
declare module 'react-tether/src/react-tether.js' {
  declare module.exports: $Exports<'react-tether/src/react-tether'>;
}
declare module 'react-tether/src/TetherComponent.jsx' {
  declare module.exports: $Exports<'react-tether/src/TetherComponent'>;
}
declare module 'react-tether/tests/test.js' {
  declare module.exports: $Exports<'react-tether/tests/test'>;
}
declare module 'react-tether/webpack.banner.js' {
  declare module.exports: $Exports<'react-tether/webpack.banner'>;
}
declare module 'react-tether/webpack.config.js' {
  declare module.exports: $Exports<'react-tether/webpack.config'>;
}
declare module 'react-tether/webpack.prod.config.js' {
  declare module.exports: $Exports<'react-tether/webpack.prod.config'>;
}
