// flow-typed signature: cded1d1ae84916eb4a986fb216792f49
// flow-typed version: <<STUB>>/react-animate-height_v2.0.4/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-animate-height'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-animate-height' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-animate-height/lib/AnimateHeight' {
  declare module.exports: any;
}

declare module 'react-animate-height/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-animate-height/lib/AnimateHeight.js' {
  declare module.exports: $Exports<'react-animate-height/lib/AnimateHeight'>;
}
declare module 'react-animate-height/lib/index.js' {
  declare module.exports: $Exports<'react-animate-height/lib/index'>;
}
