// flow-typed signature: c5888f34b2ce18c883dd81adaf9dcd57
// flow-typed version: <<STUB>>/react-scrollbars-custom_v4.0/flow_v0.93.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-scrollbars-custom'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-scrollbars-custom' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-scrollbars-custom/dist/rsc.esm' {
  declare module.exports: any;
}

declare module 'react-scrollbars-custom/dist/rsc' {
  declare module.exports: any;
}

declare module 'react-scrollbars-custom/dist/rsc.next.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-scrollbars-custom/dist/rsc.esm.js' {
  declare module.exports: $Exports<'react-scrollbars-custom/dist/rsc.esm'>;
}
declare module 'react-scrollbars-custom/dist/rsc.js' {
  declare module.exports: $Exports<'react-scrollbars-custom/dist/rsc'>;
}
declare module 'react-scrollbars-custom/dist/rsc.next.esm.js' {
  declare module.exports: $Exports<'react-scrollbars-custom/dist/rsc.next.esm'>;
}
