// flow-typed signature: 28ec8eaa651faef2d3ebcde79729d2f0
// flow-typed version: <<STUB>>/react-beautiful-dnd_v9.0.2/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-beautiful-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-beautiful-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.cjs' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.esm' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/dist/react-beautiful-dnd' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.min' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/middleware/action-timing-average' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/middleware/action-timing' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/middleware/log' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/middleware/user-timing' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/debug/timings' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/action-creators' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/auto-scroller-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/can-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/get-best-scrollable-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/auto-scroller/jump-scroller' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/axis' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/can-start-drag' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/create-store' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension-marshal/publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension-structures' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/droppable-dimension' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-displacement-map' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-draggables-inside-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-droppable-over' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-home-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-home-location' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-max-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-new-home-client-border-box-center' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-page-item-positions' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/is-movement-allowed' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/is-within' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/auto-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/dimension-marshal-stopper' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/drop-animation-finish' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/drop' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/hooks' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/lift' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/max-scroll-updater' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/pending-drop' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/style' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/middleware/util/message-preset' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-best-cross-axis-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-closest-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-cross-axis-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/get-forced-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/in-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/in-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/is-totally-visible-in-new-location' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/move-to-next-index-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-to-edge' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/no-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/publish/get-dimension-map' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/publish/get-drag-positions' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/publish/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/reducer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/scroll-viewport' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/spacing' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/store-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/visibility/is-partially-visible-through-frame' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/visibility/is-position-in-frame' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/visibility/is-totally-visible-through-frame' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/visibility/is-visible' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/with-droppable-displacement' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/with-droppable-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/animation' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/announcer/announcer-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/announcer/announcer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/context-keys' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/data-attributes' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-keyboard-sensor' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-mouse-sensor' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-touch-sensor' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/sensor-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/bind-events' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-event-marshal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-post-drag-event-preventer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-scheduler' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/event-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/focus-retainer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/get-drag-handle-ref' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/is-sloppy-click-threshold-exceeded' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/prevent-standard-key-events' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/should-allow-dragging-from-target' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/util/supported-page-visibility-event-name' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/connected-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/draggable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/connected-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/droppable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-border-box-center-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-closest-scrollable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-window-from-ref' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/is-strict-equal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/key-codes' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/moveable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/moveable/moveable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/moveable/moveable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/placeholder/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/placeholder/placeholder-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/placeholder/placeholder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/style-marshal/get-styles' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/style-marshal/style-marshal-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/style-marshal/style-marshal' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/throw-if-invalid-inner-ref' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/window/get-viewport' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/window/get-window-from-ref' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/window/get-window-scroll' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/window/scroll-window' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.cjs.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/dist/react-beautiful-dnd.cjs'>;
}
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.esm.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/dist/react-beautiful-dnd.esm'>;
}
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/dist/react-beautiful-dnd'>;
}
declare module 'react-beautiful-dnd/dist/react-beautiful-dnd.min.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/dist/react-beautiful-dnd.min'>;
}
declare module 'react-beautiful-dnd/src/debug/middleware/action-timing-average.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/middleware/action-timing-average'>;
}
declare module 'react-beautiful-dnd/src/debug/middleware/action-timing.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/middleware/action-timing'>;
}
declare module 'react-beautiful-dnd/src/debug/middleware/log.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/middleware/log'>;
}
declare module 'react-beautiful-dnd/src/debug/middleware/user-timing.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/middleware/user-timing'>;
}
declare module 'react-beautiful-dnd/src/debug/timings.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/debug/timings'>;
}
declare module 'react-beautiful-dnd/src/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/index'>;
}
declare module 'react-beautiful-dnd/src/state/action-creators.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/action-creators'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/auto-scroller-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/auto-scroller-types'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/can-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/can-scroll'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/fluid-scroller'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/get-best-scrollable-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/get-best-scrollable-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/index'>;
}
declare module 'react-beautiful-dnd/src/state/auto-scroller/jump-scroller.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/auto-scroller/jump-scroller'>;
}
declare module 'react-beautiful-dnd/src/state/axis.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/axis'>;
}
declare module 'react-beautiful-dnd/src/state/can-start-drag.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/can-start-drag'>;
}
declare module 'react-beautiful-dnd/src/state/create-store.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/create-store'>;
}
declare module 'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal-types'>;
}
declare module 'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension-marshal/dimension-marshal'>;
}
declare module 'react-beautiful-dnd/src/state/dimension-marshal/publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension-marshal/publisher'>;
}
declare module 'react-beautiful-dnd/src/state/dimension-structures.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension-structures'>;
}
declare module 'react-beautiful-dnd/src/state/droppable-dimension.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/droppable-dimension'>;
}
declare module 'react-beautiful-dnd/src/state/get-displacement-map.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-displacement-map'>;
}
declare module 'react-beautiful-dnd/src/state/get-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-displacement'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/in-foreign-list'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/in-home-list'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/index'>;
}
declare module 'react-beautiful-dnd/src/state/get-draggables-inside-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-draggables-inside-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/get-droppable-over.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-droppable-over'>;
}
declare module 'react-beautiful-dnd/src/state/get-home-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-home-impact'>;
}
declare module 'react-beautiful-dnd/src/state/get-home-location.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-home-location'>;
}
declare module 'react-beautiful-dnd/src/state/get-max-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-max-scroll'>;
}
declare module 'react-beautiful-dnd/src/state/get-new-home-client-border-box-center.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-new-home-client-border-box-center'>;
}
declare module 'react-beautiful-dnd/src/state/get-page-item-positions.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-page-item-positions'>;
}
declare module 'react-beautiful-dnd/src/state/is-movement-allowed.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/is-movement-allowed'>;
}
declare module 'react-beautiful-dnd/src/state/is-within.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/is-within'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/auto-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/auto-scroll'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/dimension-marshal-stopper.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/dimension-marshal-stopper'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/drop-animation-finish.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/drop-animation-finish'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/drop.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/drop'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/hooks.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/hooks'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/lift.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/lift'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/max-scroll-updater.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/max-scroll-updater'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/pending-drop.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/pending-drop'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/style.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/style'>;
}
declare module 'react-beautiful-dnd/src/state/middleware/util/message-preset.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/middleware/util/message-preset'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-best-cross-axis-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-best-cross-axis-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-closest-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/get-closest-draggable'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-cross-axis-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-cross-axis-types'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-foreign-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-cross-axis/move-to-new-droppable/to-home-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/get-forced-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/get-forced-displacement'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/in-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/in-foreign-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/in-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/in-home-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/is-totally-visible-in-new-location.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/is-totally-visible-in-new-location'>;
}
declare module 'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/move-to-next-index-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-in-direction/move-to-next-index/move-to-next-index-types'>;
}
declare module 'react-beautiful-dnd/src/state/move-to-edge.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-to-edge'>;
}
declare module 'react-beautiful-dnd/src/state/no-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/no-impact'>;
}
declare module 'react-beautiful-dnd/src/state/position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/position'>;
}
declare module 'react-beautiful-dnd/src/state/publish/get-dimension-map.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/publish/get-dimension-map'>;
}
declare module 'react-beautiful-dnd/src/state/publish/get-drag-positions.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/publish/get-drag-positions'>;
}
declare module 'react-beautiful-dnd/src/state/publish/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/publish/index'>;
}
declare module 'react-beautiful-dnd/src/state/reducer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/reducer'>;
}
declare module 'react-beautiful-dnd/src/state/scroll-viewport.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/scroll-viewport'>;
}
declare module 'react-beautiful-dnd/src/state/spacing.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/spacing'>;
}
declare module 'react-beautiful-dnd/src/state/store-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/store-types'>;
}
declare module 'react-beautiful-dnd/src/state/visibility/is-partially-visible-through-frame.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/visibility/is-partially-visible-through-frame'>;
}
declare module 'react-beautiful-dnd/src/state/visibility/is-position-in-frame.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/visibility/is-position-in-frame'>;
}
declare module 'react-beautiful-dnd/src/state/visibility/is-totally-visible-through-frame.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/visibility/is-totally-visible-through-frame'>;
}
declare module 'react-beautiful-dnd/src/state/visibility/is-visible.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/visibility/is-visible'>;
}
declare module 'react-beautiful-dnd/src/state/with-droppable-displacement.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/with-droppable-displacement'>;
}
declare module 'react-beautiful-dnd/src/state/with-droppable-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/with-droppable-scroll'>;
}
declare module 'react-beautiful-dnd/src/types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/types'>;
}
declare module 'react-beautiful-dnd/src/view/animation.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/animation'>;
}
declare module 'react-beautiful-dnd/src/view/announcer/announcer-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/announcer/announcer-types'>;
}
declare module 'react-beautiful-dnd/src/view/announcer/announcer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/announcer/announcer'>;
}
declare module 'react-beautiful-dnd/src/view/context-keys.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/context-keys'>;
}
declare module 'react-beautiful-dnd/src/view/data-attributes.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/data-attributes'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/index'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/drag-handle-types'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/drag-handle'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/index'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-keyboard-sensor.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/sensor/create-keyboard-sensor'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-mouse-sensor.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/sensor/create-mouse-sensor'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/create-touch-sensor.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/sensor/create-touch-sensor'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/sensor/sensor-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/sensor/sensor-types'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/bind-events.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/bind-events'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-event-marshal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/create-event-marshal'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-post-drag-event-preventer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/create-post-drag-event-preventer'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/create-scheduler.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/create-scheduler'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/event-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/event-types'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/focus-retainer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/focus-retainer'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/get-drag-handle-ref.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/get-drag-handle-ref'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/is-sloppy-click-threshold-exceeded.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/is-sloppy-click-threshold-exceeded'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/prevent-standard-key-events.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/prevent-standard-key-events'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/should-allow-dragging-from-target.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/should-allow-dragging-from-target'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/util/supported-page-visibility-event-name.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/util/supported-page-visibility-event-name'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/connected-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/connected-draggable'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/draggable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/draggable-types'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/draggable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/draggable'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/index'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/connected-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/connected-droppable'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/droppable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/droppable-types'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/droppable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/droppable'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/index'>;
}
declare module 'react-beautiful-dnd/src/view/get-border-box-center-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-border-box-center-position'>;
}
declare module 'react-beautiful-dnd/src/view/get-closest-scrollable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-closest-scrollable'>;
}
declare module 'react-beautiful-dnd/src/view/get-window-from-ref.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-window-from-ref'>;
}
declare module 'react-beautiful-dnd/src/view/is-strict-equal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/is-strict-equal'>;
}
declare module 'react-beautiful-dnd/src/view/key-codes.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/key-codes'>;
}
declare module 'react-beautiful-dnd/src/view/moveable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/moveable/index'>;
}
declare module 'react-beautiful-dnd/src/view/moveable/moveable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/moveable/moveable-types'>;
}
declare module 'react-beautiful-dnd/src/view/moveable/moveable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/moveable/moveable'>;
}
declare module 'react-beautiful-dnd/src/view/placeholder/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/placeholder/index'>;
}
declare module 'react-beautiful-dnd/src/view/placeholder/placeholder-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/placeholder/placeholder-types'>;
}
declare module 'react-beautiful-dnd/src/view/placeholder/placeholder.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/placeholder/placeholder'>;
}
declare module 'react-beautiful-dnd/src/view/style-marshal/get-styles.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/style-marshal/get-styles'>;
}
declare module 'react-beautiful-dnd/src/view/style-marshal/style-marshal-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/style-marshal/style-marshal-types'>;
}
declare module 'react-beautiful-dnd/src/view/style-marshal/style-marshal.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/style-marshal/style-marshal'>;
}
declare module 'react-beautiful-dnd/src/view/throw-if-invalid-inner-ref.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/throw-if-invalid-inner-ref'>;
}
declare module 'react-beautiful-dnd/src/view/window/get-viewport.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/window/get-viewport'>;
}
declare module 'react-beautiful-dnd/src/view/window/get-window-from-ref.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/window/get-window-from-ref'>;
}
declare module 'react-beautiful-dnd/src/view/window/get-window-scroll.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/window/get-window-scroll'>;
}
declare module 'react-beautiful-dnd/src/view/window/scroll-window.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/window/scroll-window'>;
}
