// flow-typed signature: 9efd6dedd0199f74b47efaae171c70d1
// flow-typed version: <<STUB>>/sanitize-html_v1.21.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sanitize-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sanitize-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sanitize-html/dist/sanitize-html-es2015' {
  declare module.exports: any;
}

declare module 'sanitize-html/dist/sanitize-html' {
  declare module.exports: any;
}

declare module 'sanitize-html/dist/sanitize-html.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sanitize-html/dist/sanitize-html-es2015.js' {
  declare module.exports: $Exports<'sanitize-html/dist/sanitize-html-es2015'>;
}
declare module 'sanitize-html/dist/sanitize-html.js' {
  declare module.exports: $Exports<'sanitize-html/dist/sanitize-html'>;
}
declare module 'sanitize-html/dist/sanitize-html.min.js' {
  declare module.exports: $Exports<'sanitize-html/dist/sanitize-html.min'>;
}
