// flow-typed signature: de9eb4e392e44cebc595883cbed97ea0
// flow-typed version: <<STUB>>/scroll-into-view-if-needed_v1.2.1/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scroll-into-view-if-needed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scroll-into-view-if-needed' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scroll-into-view-if-needed/dist/bundle' {
  declare module.exports: any;
}

declare module 'scroll-into-view-if-needed/dist/index' {
  declare module.exports: any;
}

declare module 'scroll-into-view-if-needed/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scroll-into-view-if-needed/dist/bundle.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/dist/bundle'>;
}
declare module 'scroll-into-view-if-needed/dist/index.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/dist/index'>;
}
declare module 'scroll-into-view-if-needed/rollup.config.js' {
  declare module.exports: $Exports<'scroll-into-view-if-needed/rollup.config'>;
}
