// flow-typed signature: c11d951f7fa600a4531c52d0853ebafe
// flow-typed version: <<STUB>>/tabbable_v1.1.0/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tabbable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tabbable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tabbable/karma.conf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tabbable/index' {
  declare module.exports: $Exports<'tabbable'>;
}
declare module 'tabbable/index.js' {
  declare module.exports: $Exports<'tabbable'>;
}
declare module 'tabbable/karma.conf.js' {
  declare module.exports: $Exports<'tabbable/karma.conf'>;
}
