// flow-typed signature: 9825936188007502f99dd281c466170f
// flow-typed version: <<STUB>>/uuid_v^8.3.2/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uuid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uuid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'uuid/dist/esm-browser' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/md5' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/nil' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/parse' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/regex' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/rng' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/sha1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/stringify' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v3' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v35' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v4' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/v5' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/validate' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-browser/version' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/md5' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/nil' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/parse' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/regex' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/rng' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/sha1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/stringify' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/v1' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/v3' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/v35' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/v4' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/v5' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/validate' {
  declare module.exports: any;
}

declare module 'uuid/dist/esm-node/version' {
  declare module.exports: any;
}

declare module 'uuid/dist' {
  declare module.exports: any;
}

declare module 'uuid/dist/md5-browser' {
  declare module.exports: any;
}

declare module 'uuid/dist/md5' {
  declare module.exports: any;
}

declare module 'uuid/dist/nil' {
  declare module.exports: any;
}

declare module 'uuid/dist/parse' {
  declare module.exports: any;
}

declare module 'uuid/dist/regex' {
  declare module.exports: any;
}

declare module 'uuid/dist/rng-browser' {
  declare module.exports: any;
}

declare module 'uuid/dist/rng' {
  declare module.exports: any;
}

declare module 'uuid/dist/sha1-browser' {
  declare module.exports: any;
}

declare module 'uuid/dist/sha1' {
  declare module.exports: any;
}

declare module 'uuid/dist/stringify' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuid.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuidNIL.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuidParse.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuidStringify.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuidv1.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuidv3.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuidv4.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuidv5.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuidValidate.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/umd/uuidVersion.min' {
  declare module.exports: any;
}

declare module 'uuid/dist/uuid-bin' {
  declare module.exports: any;
}

declare module 'uuid/dist/v1' {
  declare module.exports: any;
}

declare module 'uuid/dist/v3' {
  declare module.exports: any;
}

declare module 'uuid/dist/v35' {
  declare module.exports: any;
}

declare module 'uuid/dist/v4' {
  declare module.exports: any;
}

declare module 'uuid/dist/v5' {
  declare module.exports: any;
}

declare module 'uuid/dist/validate' {
  declare module.exports: any;
}

declare module 'uuid/dist/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'uuid/dist/esm-browser/index' {
  declare module.exports: $Exports<'uuid/dist/esm-browser'>;
}
declare module 'uuid/dist/esm-browser/index.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser'>;
}
declare module 'uuid/dist/esm-browser/md5.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/md5'>;
}
declare module 'uuid/dist/esm-browser/nil.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/nil'>;
}
declare module 'uuid/dist/esm-browser/parse.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/parse'>;
}
declare module 'uuid/dist/esm-browser/regex.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/regex'>;
}
declare module 'uuid/dist/esm-browser/rng.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/rng'>;
}
declare module 'uuid/dist/esm-browser/sha1.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/sha1'>;
}
declare module 'uuid/dist/esm-browser/stringify.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/stringify'>;
}
declare module 'uuid/dist/esm-browser/v1.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v1'>;
}
declare module 'uuid/dist/esm-browser/v3.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v3'>;
}
declare module 'uuid/dist/esm-browser/v35.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v35'>;
}
declare module 'uuid/dist/esm-browser/v4.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v4'>;
}
declare module 'uuid/dist/esm-browser/v5.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/v5'>;
}
declare module 'uuid/dist/esm-browser/validate.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/validate'>;
}
declare module 'uuid/dist/esm-browser/version.js' {
  declare module.exports: $Exports<'uuid/dist/esm-browser/version'>;
}
declare module 'uuid/dist/esm-node/index' {
  declare module.exports: $Exports<'uuid/dist/esm-node'>;
}
declare module 'uuid/dist/esm-node/index.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node'>;
}
declare module 'uuid/dist/esm-node/md5.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/md5'>;
}
declare module 'uuid/dist/esm-node/nil.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/nil'>;
}
declare module 'uuid/dist/esm-node/parse.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/parse'>;
}
declare module 'uuid/dist/esm-node/regex.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/regex'>;
}
declare module 'uuid/dist/esm-node/rng.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/rng'>;
}
declare module 'uuid/dist/esm-node/sha1.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/sha1'>;
}
declare module 'uuid/dist/esm-node/stringify.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/stringify'>;
}
declare module 'uuid/dist/esm-node/v1.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/v1'>;
}
declare module 'uuid/dist/esm-node/v3.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/v3'>;
}
declare module 'uuid/dist/esm-node/v35.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/v35'>;
}
declare module 'uuid/dist/esm-node/v4.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/v4'>;
}
declare module 'uuid/dist/esm-node/v5.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/v5'>;
}
declare module 'uuid/dist/esm-node/validate.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/validate'>;
}
declare module 'uuid/dist/esm-node/version.js' {
  declare module.exports: $Exports<'uuid/dist/esm-node/version'>;
}
declare module 'uuid/dist/index' {
  declare module.exports: $Exports<'uuid/dist'>;
}
declare module 'uuid/dist/index.js' {
  declare module.exports: $Exports<'uuid/dist'>;
}
declare module 'uuid/dist/md5-browser.js' {
  declare module.exports: $Exports<'uuid/dist/md5-browser'>;
}
declare module 'uuid/dist/md5.js' {
  declare module.exports: $Exports<'uuid/dist/md5'>;
}
declare module 'uuid/dist/nil.js' {
  declare module.exports: $Exports<'uuid/dist/nil'>;
}
declare module 'uuid/dist/parse.js' {
  declare module.exports: $Exports<'uuid/dist/parse'>;
}
declare module 'uuid/dist/regex.js' {
  declare module.exports: $Exports<'uuid/dist/regex'>;
}
declare module 'uuid/dist/rng-browser.js' {
  declare module.exports: $Exports<'uuid/dist/rng-browser'>;
}
declare module 'uuid/dist/rng.js' {
  declare module.exports: $Exports<'uuid/dist/rng'>;
}
declare module 'uuid/dist/sha1-browser.js' {
  declare module.exports: $Exports<'uuid/dist/sha1-browser'>;
}
declare module 'uuid/dist/sha1.js' {
  declare module.exports: $Exports<'uuid/dist/sha1'>;
}
declare module 'uuid/dist/stringify.js' {
  declare module.exports: $Exports<'uuid/dist/stringify'>;
}
declare module 'uuid/dist/umd/uuid.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuid.min'>;
}
declare module 'uuid/dist/umd/uuidNIL.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuidNIL.min'>;
}
declare module 'uuid/dist/umd/uuidParse.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuidParse.min'>;
}
declare module 'uuid/dist/umd/uuidStringify.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuidStringify.min'>;
}
declare module 'uuid/dist/umd/uuidv1.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuidv1.min'>;
}
declare module 'uuid/dist/umd/uuidv3.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuidv3.min'>;
}
declare module 'uuid/dist/umd/uuidv4.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuidv4.min'>;
}
declare module 'uuid/dist/umd/uuidv5.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuidv5.min'>;
}
declare module 'uuid/dist/umd/uuidValidate.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuidValidate.min'>;
}
declare module 'uuid/dist/umd/uuidVersion.min.js' {
  declare module.exports: $Exports<'uuid/dist/umd/uuidVersion.min'>;
}
declare module 'uuid/dist/uuid-bin.js' {
  declare module.exports: $Exports<'uuid/dist/uuid-bin'>;
}
declare module 'uuid/dist/v1.js' {
  declare module.exports: $Exports<'uuid/dist/v1'>;
}
declare module 'uuid/dist/v3.js' {
  declare module.exports: $Exports<'uuid/dist/v3'>;
}
declare module 'uuid/dist/v35.js' {
  declare module.exports: $Exports<'uuid/dist/v35'>;
}
declare module 'uuid/dist/v4.js' {
  declare module.exports: $Exports<'uuid/dist/v4'>;
}
declare module 'uuid/dist/v5.js' {
  declare module.exports: $Exports<'uuid/dist/v5'>;
}
declare module 'uuid/dist/validate.js' {
  declare module.exports: $Exports<'uuid/dist/validate'>;
}
declare module 'uuid/dist/version.js' {
  declare module.exports: $Exports<'uuid/dist/version'>;
}
