const mockSubfolder = {
    type: 'folder',
    id: '73426618530',
    etag: '3',
    name: 'An Ordered Folder',
    size: 202621773,
    parent: {
        type: 'folder',
        id: '69083462919',
        sequence_id: '2',
        etag: '2',
        name: 'Preview Test Folder',
    },
    permissions: {
        can_download: true,
        can_upload: false,
        can_rename: false,
        can_delete: false,
        can_share: false,
        can_invite_collaborator: false,
        can_set_share_access: false,
    },
    path_collection: {
        total_count: 2,
        entries: [
            {
                type: 'folder',
                id: '0',
                sequence_id: null,
                etag: null,
                name: 'All Files',
            },
            {
                type: 'folder',
                id: '69083462919',
                sequence_id: '2',
                etag: '2',
                name: 'Preview Test Folder',
            },
        ],
    },
    modified_at: '2019-04-16T15:44:44-07:00',
    created_at: '2019-04-16T15:44:14-07:00',
    modified_by: {
        type: 'user',
        id: '7503712462',
        name: 'Preview',
        login: 'preview@boxdemo.com',
    },
    has_collaborations: true,
    is_externally_owned: false,
    shared_link: null,
    watermark_info: {
        is_watermarked: false,
    },
    item_collection: {
        total_count: 1,
        entries: [
            {
                type: 'file',
                id: '441230776830',
                etag: '1',
                name: 'Audio.mp3',
                size: 2772151,
                parent: {
                    type: 'folder',
                    id: '73426618530',
                    sequence_id: '3',
                    etag: '3',
                    name: 'An Ordered Folder',
                },
                extension: 'mp3',
                permissions: {
                    can_download: true,
                    can_preview: true,
                    can_upload: false,
                    can_comment: true,
                    can_rename: false,
                    can_delete: false,
                    can_share: false,
                    can_set_share_access: false,
                    can_invite_collaborator: false,
                    can_annotate: false,
                    can_view_annotations_all: true,
                    can_view_annotations_self: true,
                    can_create_annotations: false,
                    can_view_annotations: false,
                },
                path_collection: {
                    total_count: 3,
                    entries: [
                        {
                            type: 'folder',
                            id: '0',
                            sequence_id: null,
                            etag: null,
                            name: 'All Files',
                        },
                        {
                            type: 'folder',
                            id: '69083462919',
                            sequence_id: '2',
                            etag: '2',
                            name: 'Preview Test Folder',
                        },
                        {
                            type: 'folder',
                            id: '73426618530',
                            sequence_id: '3',
                            etag: '3',
                            name: 'An Ordered Folder',
                        },
                    ],
                },
                modified_at: '2022-12-12T19:18:24-08:00',
                created_at: '2019-04-16T15:44:18-07:00',
                modified_by: {
                    type: 'user',
                    id: '7503712462',
                    name: 'Preview',
                    login: 'preview@boxdemo.com',
                },
                has_collaborations: true,
                is_externally_owned: false,
                authenticated_download_url: 'https://dl.boxcloud.com/api/2.0/files/441230776830/content',
                is_download_available: true,
                representations: {
                    entries: [],
                },
                file_version: {
                    type: 'file_version',
                    id: '466700608830',
                    sha1: '4822f5ede0fd9f08c31874b850a7ba632f564006',
                },
                sha1: '4822f5ede0fd9f08c31874b850a7ba632f564006',
                shared_link: null,
                watermark_info: {
                    is_watermarked: false,
                },
            },
        ],
        offset: 0,
        limit: 50,
        order: [
            {
                by: 'type',
                direction: 'ASC',
            },
            {
                by: 'name',
                direction: 'ASC',
            },
        ],
    },
};

export default mockSubfolder;
