// include a block comment letting developers know that these icons shouldn't
// be edited, and where to ask for changes or updates
module.exports = function addAutoGeneratedMessage(file) {
    const updatedFile = file.replace(
        'const __add_documentation = true;',
        `
/**
 * This is an auto-generated component and should not be edited
 * manually in contributor pull requests.
 *
 * If you have problems with this component:
 * - https://github.com/box/box-ui-elements/issues/new?template=Bug_report.md
 *
 * If there are missing features in this component:
 * - https://github.com/box/box-ui-elements/issues/new?template=Feature_request.md
 */`,
    );
    return updatedFile;
};
