import {
    FIELD_COLLECTIONS,
    FIELD_FILE_VERSION,
    FIELD_LOCK,
    FIELD_SHA1,
    FIELD_SHARED_LINK,
    FIELD_WATERMARK_INFO,
    FIELD_VERSION_NUMBER
} from '../../constants';
import { FOLDER_FIELDS_TO_FETCH } from '../../utils/fields';

// Fields needed for Content Explorer folder requests
const CONTENT_EXPLORER_FOLDER_FIELDS_TO_FETCH = [
    ...FOLDER_FIELDS_TO_FETCH,
    FIELD_FILE_VERSION,
    FIELD_SHA1,
    FIELD_SHARED_LINK,
    FIELD_WATERMARK_INFO,
    FIELD_COLLECTIONS,
    FIELD_LOCK,
    FIELD_VERSION_NUMBER
];

export default CONTENT_EXPLORER_FOLDER_FIELDS_TO_FETCH;
