// flow-typed signature: 2040cc63447bfe6a5167450ad1ff3eb0
// flow-typed version: <<STUB>>/@sambego/storybook-state_v1.3.6/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sambego/storybook-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sambego/storybook-state' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sambego/storybook-state/dist' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/dist/State' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/dist/StateDecorator' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/dist/Store' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/enzyme.config' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/jest.config' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/src' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/src/State' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/src/StateDecorator' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/src/Store' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/tests/State.test' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/tests/StateDecorator.test' {
  declare module.exports: any;
}

declare module '@sambego/storybook-state/tests/Store.test' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sambego/storybook-state/dist/index' {
  declare module.exports: $Exports<'@sambego/storybook-state/dist'>;
}
declare module '@sambego/storybook-state/dist/index.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/dist'>;
}
declare module '@sambego/storybook-state/dist/State.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/dist/State'>;
}
declare module '@sambego/storybook-state/dist/StateDecorator.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/dist/StateDecorator'>;
}
declare module '@sambego/storybook-state/dist/Store.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/dist/Store'>;
}
declare module '@sambego/storybook-state/enzyme.config.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/enzyme.config'>;
}
declare module '@sambego/storybook-state/jest.config.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/jest.config'>;
}
declare module '@sambego/storybook-state/src/index' {
  declare module.exports: $Exports<'@sambego/storybook-state/src'>;
}
declare module '@sambego/storybook-state/src/index.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/src'>;
}
declare module '@sambego/storybook-state/src/State.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/src/State'>;
}
declare module '@sambego/storybook-state/src/StateDecorator.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/src/StateDecorator'>;
}
declare module '@sambego/storybook-state/src/Store.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/src/Store'>;
}
declare module '@sambego/storybook-state/tests/State.test.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/tests/State.test'>;
}
declare module '@sambego/storybook-state/tests/StateDecorator.test.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/tests/StateDecorator.test'>;
}
declare module '@sambego/storybook-state/tests/Store.test.js' {
  declare module.exports: $Exports<'@sambego/storybook-state/tests/Store.test'>;
}
