const ROW_HEIGHT = 50;
const FIXED_ROW_COUNT = 1;

const NEED_REFINING = 'needRefining';
const TOO_MANY_RESULTS = 'tooManyResults';
const NO_ACCESS_FOR_QUERY = 'noAccessForQuery';
const NO_ACCESS_FOR_TEMPLATE = 'noAccessForTemplate';

export { FIXED_ROW_COUNT, ROW_HEIGHT, NEED_REFINING, TOO_MANY_RESULTS, NO_ACCESS_FOR_QUERY, NO_ACCESS_FOR_TEMPLATE };
