const ITEM_TYPE_FILE = 'file';
const ITEM_TYPE_FOLDER = 'folder';
const ITEM_TYPE_HUBS = 'hubs';
const ITEM_TYPE_WEBLINK = 'web_link';
const JSON_PATCH_OP_ADD = 'add';
const JSON_PATCH_OP_REMOVE = 'remove';
const JSON_PATCH_OP_REPLACE = 'replace';
const JSON_PATCH_OP_TEST = 'test';
const METADATA_FIELD_TYPE_ENUM = 'enum';
const METADATA_FIELD_TYPE_MULTISELECT = 'multiSelect';
export { ITEM_TYPE_FILE, ITEM_TYPE_FOLDER, ITEM_TYPE_HUBS, ITEM_TYPE_WEBLINK, JSON_PATCH_OP_ADD, JSON_PATCH_OP_REMOVE, JSON_PATCH_OP_REPLACE, JSON_PATCH_OP_TEST, METADATA_FIELD_TYPE_ENUM, METADATA_FIELD_TYPE_MULTISELECT };
//# sourceMappingURL=constants.js.map