#!/usr/bin/env node

/* eslint-disable no-console */

// Applies the baselines regenerated by the latest CircleCI `visual-tests` job of a pull request.
// Usage: yarn test:visual:download <pull request number | branch name>

const { execSync } = require('child_process');
const path = require('path');

const PROJECT_API = 'https://circleci.com/api/v1.1/project/github/box/box-ui-elements';
const JOB_NAME = 'visual-tests';
const BASELINES_ARTIFACT = 'visual/visual-baselines.tgz';
const REPO_ROOT = path.resolve(__dirname, '..');

async function getJson(url) {
    const response = await fetch(url);
    if (!response.ok) {
        throw new Error(`${url} responded with ${response.status}`);
    }
    return response.json();
}

async function main() {
    const target = process.argv[2];
    if (!target) {
        throw new Error('Pass a pull request number or a branch name, e.g. `yarn test:visual:download 4887`.');
    }
    const branch = /^\d+$/.test(target) ? `pull/${target}` : target;

    const builds = await getJson(`${PROJECT_API}/tree/${encodeURIComponent(branch)}?limit=50&shallow=true`);
    const job = builds.find(build => build.workflows && build.workflows.job_name === JOB_NAME);
    if (!job) {
        throw new Error(`No ${JOB_NAME} job found for ${branch}.`);
    }
    console.log(
        `Latest ${JOB_NAME} job for ${branch}: ${job.build_url} (${job.status}, ${job.vcs_revision.slice(0, 9)})`,
    );

    const head = execSync('git rev-parse HEAD', { cwd: REPO_ROOT, encoding: 'utf8' }).trim();
    if (head !== job.vcs_revision) {
        console.warn(`Warning: that job ran on ${job.vcs_revision.slice(0, 9)}, but your HEAD is ${head.slice(0, 9)}.`);
    }

    const artifacts = await getJson(`${PROJECT_API}/${job.build_num}/artifacts`);
    const baselines = artifacts.find(artifact => artifact.path === BASELINES_ARTIFACT);
    if (!baselines) {
        console.log('That job did not regenerate any baselines.');
        return;
    }

    const archive = Buffer.from(await (await fetch(baselines.url)).arrayBuffer());
    execSync('tar -xzf -', { cwd: REPO_ROOT, input: archive });
    const files = execSync('tar -tzf -', { input: archive, encoding: 'utf8' });
    console.log(`Updated baselines:\n${files.replace(/^(?=.)/gm, '  ')}`);
    console.log('Review them with `git diff --stat`, then commit the PNGs.');
}

main().catch(error => {
    console.error(error.message);
    process.exit(1);
});
