import { IntlProvider } from 'react-intl';
import Avatar from '../src/components/avatar/Avatar';
import Button from '../src/components/button/Button';
import DatalistItem from '../src/components/datalist-item/DatalistItem';
import Flyout from '../src/components/flyout/Flyout';
import Label from '../src/components/label/Label';
import Link from '../src/components/link/Link';
import ModalActions from '../src/components/modal/ModalActions';
import ModalDialog from '../src/components/modal/ModalDialog';
import Overlay from '../src/components/flyout/Overlay';
import PlainButton from '../src/components/plain-button/PlainButton';
import PrimaryButton from '../src/components/primary-button/PrimaryButton';
import QuickSearch from '../src/features/quick-search/QuickSearch';
import QuickSearchItem from '../src/features/quick-search/QuickSearchItem';
import TextArea from '../src/components/text-area/TextArea';
import TextInput from '../src/components/text-input/TextInput';

global.IntlProvider = IntlProvider;
global.Avatar = Avatar;
global.Button = Button;
global.DatalistItem = DatalistItem;
global.Flyout = Flyout;
global.Label = Label;
global.Link = Link;
global.ModalActions = ModalActions;
global.ModalDialog = ModalDialog;
global.Overlay = Overlay;
global.PlainButton = PlainButton;
global.PrimaryButton = PrimaryButton;
global.QuickSearch = QuickSearch;
global.QuickSearchItem = QuickSearchItem;
global.TextArea = TextArea;
global.TextInput = TextInput;
