// flow-typed signature: 0c1d7f4e07dcdead3567dc508516abb3
// flow-typed version: <<STUB>>/@storybook/addon-actions_v5.x.x/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'storybook/actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'storybook/actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'storybook/actions/dist/components/ActionLogger' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/constants' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/containers/ActionLogger' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/manager' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/models/ActionDisplay' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/models/ActionOptions' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/models/ActionsFunction' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/models/ActionsMap' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/models/DecoratorFunction' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/models/HandlerFunction' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/models' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/preview/action' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/preview/actions' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/preview/configureActions' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/preview/decorateAction' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/preview' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/preview/withActions' {
  declare module.exports: any;
}

declare module 'storybook/actions/dist/typings.d' {
  declare module.exports: any;
}

declare module 'storybook/actions/register' {
  declare module.exports: any;
}

// Filename aliases
declare module 'storybook/actions/dist/components/ActionLogger/index' {
  declare module.exports: $Exports<'storybook/actions/dist/components/ActionLogger'>;
}
declare module 'storybook/actions/dist/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'storybook/actions/dist/components/ActionLogger'>;
}
declare module 'storybook/actions/dist/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'storybook/actions/dist/components/ActionLogger/style'>;
}
declare module 'storybook/actions/dist/constants.js' {
  declare module.exports: $Exports<'storybook/actions/dist/constants'>;
}
declare module 'storybook/actions/dist/containers/ActionLogger/index' {
  declare module.exports: $Exports<'storybook/actions/dist/containers/ActionLogger'>;
}
declare module 'storybook/actions/dist/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'storybook/actions/dist/containers/ActionLogger'>;
}
declare module 'storybook/actions/dist/index' {
  declare module.exports: $Exports<'storybook/actions/dist'>;
}
declare module 'storybook/actions/dist/index.js' {
  declare module.exports: $Exports<'storybook/actions/dist'>;
}
declare module 'storybook/actions/dist/manager.js' {
  declare module.exports: $Exports<'storybook/actions/dist/manager'>;
}
declare module 'storybook/actions/dist/models/ActionDisplay.js' {
  declare module.exports: $Exports<'storybook/actions/dist/models/ActionDisplay'>;
}
declare module 'storybook/actions/dist/models/ActionOptions.js' {
  declare module.exports: $Exports<'storybook/actions/dist/models/ActionOptions'>;
}
declare module 'storybook/actions/dist/models/ActionsFunction.js' {
  declare module.exports: $Exports<'storybook/actions/dist/models/ActionsFunction'>;
}
declare module 'storybook/actions/dist/models/ActionsMap.js' {
  declare module.exports: $Exports<'storybook/actions/dist/models/ActionsMap'>;
}
declare module 'storybook/actions/dist/models/DecoratorFunction.js' {
  declare module.exports: $Exports<'storybook/actions/dist/models/DecoratorFunction'>;
}
declare module 'storybook/actions/dist/models/HandlerFunction.js' {
  declare module.exports: $Exports<'storybook/actions/dist/models/HandlerFunction'>;
}
declare module 'storybook/actions/dist/models/index' {
  declare module.exports: $Exports<'storybook/actions/dist/models'>;
}
declare module 'storybook/actions/dist/models/index.js' {
  declare module.exports: $Exports<'storybook/actions/dist/models'>;
}
declare module 'storybook/actions/dist/preview/action.js' {
  declare module.exports: $Exports<'storybook/actions/dist/preview/action'>;
}
declare module 'storybook/actions/dist/preview/actions.js' {
  declare module.exports: $Exports<'storybook/actions/dist/preview/actions'>;
}
declare module 'storybook/actions/dist/preview/configureActions.js' {
  declare module.exports: $Exports<'storybook/actions/dist/preview/configureActions'>;
}
declare module 'storybook/actions/dist/preview/decorateAction.js' {
  declare module.exports: $Exports<'storybook/actions/dist/preview/decorateAction'>;
}
declare module 'storybook/actions/dist/preview/index' {
  declare module.exports: $Exports<'storybook/actions/dist/preview'>;
}
declare module 'storybook/actions/dist/preview/index.js' {
  declare module.exports: $Exports<'storybook/actions/dist/preview'>;
}
declare module 'storybook/actions/dist/preview/withActions.js' {
  declare module.exports: $Exports<'storybook/actions/dist/preview/withActions'>;
}
declare module 'storybook/actions/dist/typings.d.js' {
  declare module.exports: $Exports<'storybook/actions/dist/typings.d'>;
}
declare module 'storybook/actions/register.js' {
  declare module.exports: $Exports<'storybook/actions/register'>;
}
