// flow-typed signature: 62d1fa3393b7413fb0c607baf5861c50
// flow-typed version: <<STUB>>/@storybook/addon-viewport_v5.3.9/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-viewport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-viewport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-viewport/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/defaults' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/legacy_preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/models' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/models/Viewport' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/models/ViewportAddonParameter' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/dist/Tool' {
  declare module.exports: any;
}

declare module '@storybook/addon-viewport/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-viewport/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/constants'>;
}
declare module '@storybook/addon-viewport/dist/defaults.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/defaults'>;
}
declare module '@storybook/addon-viewport/dist/legacy_preview/index' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/legacy_preview'>;
}
declare module '@storybook/addon-viewport/dist/legacy_preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/legacy_preview'>;
}
declare module '@storybook/addon-viewport/dist/models/index' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/models'>;
}
declare module '@storybook/addon-viewport/dist/models/index.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/models'>;
}
declare module '@storybook/addon-viewport/dist/models/Viewport.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/models/Viewport'>;
}
declare module '@storybook/addon-viewport/dist/models/ViewportAddonParameter.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/models/ViewportAddonParameter'>;
}
declare module '@storybook/addon-viewport/dist/preview.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/preview'>;
}
declare module '@storybook/addon-viewport/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/register'>;
}
declare module '@storybook/addon-viewport/dist/Tool.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/dist/Tool'>;
}
declare module '@storybook/addon-viewport/register.js' {
  declare module.exports: $Exports<'@storybook/addon-viewport/register'>;
}
