name: "Quality"

on:
    pull_request_target:
        branches:
            - master
            - main
        types:
            - opened
            - edited
            - synchronize

jobs:
    coverage:
        permissions:
            checks: write
            pull-requests: write
            contents: write
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v3
            -   uses: jwalton/gh-find-current-pr@v1.3.3
                id: findPr
            -   uses: ArtiomTr/jest-coverage-report-action@v2
                with:
                    prnumber: ${{ steps.findPr.outputs.number }}
                    package-manager: yarn
                    test-script: yarn test
